### ISSUE TITLE
Tokio dependency conflict with rust-s3 0.26.4 and warp 0.3

### ISSUE THREAD

**Issue by kruserr** [durch/rust-s3#197]
**Describe the bug**
Tokio async `bucket.list` fails with the following error:
```
thread 'tokio-runtime-worker' panicked at 'not currently running on a Tokio 0.2.x runtime.'
```

**To Reproduce**

```bash
cargo init rust-s3-tokio-conflict
cd rust-s3-tokio-conflict
```

Cargo.toml
```toml
[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
rust-s3 = "0.26"
```

src/main.rs
```rust
#[tokio::main]
async fn main() {
  let bucket = s3::bucket::Bucket::new_with_path_style(
    "YOUR_BUCKET",
    s3::region::Region::Custom {
      region: "".into(),
      endpoint: "https://YOUR_DOMAIN".into(),
    },
    s3::creds::Credentials::from_env_specific(
      Some("S3_ACCESS_KEY_ID"),
      Some("S3_SECRET_ACCESS_KEY"),
      None,
      None
    ).unwrap()
  ).unwrap();

  let results = bucket.list("".to_string(), None).await.unwrap();

  println!("{:?}", results);
}
```

```bash
cargo run
```

**Expected behavior**
We should be able to use rust-s3 inside a warp 0.3 project.

**Environment**
 - rustc 1.52.0
 - rust-s3 = 0.26.4
 - minio

**Additional context**
Downgrading dependencies works but is suboptimal.
```toml
[dependencies]
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"
rust-s3 = "0.26"
```
